from __future__ import annotations

from sim_game.config import WorldConfig


DEFAULT_PRESET = "balanced"

PRESETS = {
    "balanced": WorldConfig(),
    "dry_badlands": WorldConfig(
        settlement_name="Dry Badlands",
        seed=19,
        target_turns=28,
        initial_population=110,
        starting_food=360,
        starting_water=250,
        starting_energy=320,
        starting_materials=230,
        farmland=40,
        water_infrastructure=28,
        generator_capacity=38,
        medical_capacity=10,
        housing_capacity=145,
        climate_severity=1.35,
        disease_risk=0.22,
        trade_access=0.35,
        hazard_frequency=0.45,
        research_rate=0.95,
    ),
    "trade_hub": WorldConfig(
        settlement_name="Trade Hub Delta",
        seed=77,
        target_turns=30,
        initial_population=140,
        starting_food=440,
        starting_water=410,
        starting_energy=320,
        starting_materials=320,
        farmland=42,
        water_infrastructure=40,
        generator_capacity=37,
        medical_capacity=14,
        housing_capacity=165,
        climate_severity=0.55,
        disease_risk=0.2,
        trade_access=0.9,
        hazard_frequency=0.3,
        research_rate=1.15,
    ),
    "frozen_frontier": WorldConfig(
        settlement_name="Frozen Frontier",
        seed=108,
        target_turns=26,
        initial_population=100,
        starting_food=390,
        starting_water=460,
        starting_energy=420,
        starting_materials=180,
        farmland=30,
        water_infrastructure=45,
        generator_capacity=52,
        medical_capacity=11,
        housing_capacity=130,
        climate_severity=1.1,
        disease_risk=0.34,
        trade_access=0.4,
        hazard_frequency=0.42,
        research_rate=1.05,
    ),
    "science_arcology": WorldConfig(
        settlement_name="Science Arcology",
        seed=211,
        target_turns=36,
        initial_population=150,
        starting_food=480,
        starting_water=470,
        starting_energy=420,
        starting_materials=280,
        farmland=44,
        water_infrastructure=44,
        generator_capacity=46,
        medical_capacity=20,
        housing_capacity=175,
        climate_severity=0.45,
        disease_risk=0.16,
        trade_access=0.7,
        hazard_frequency=0.25,
        research_rate=1.8,
    ),
}


def serialize_presets() -> dict[str, dict[str, object]]:
    return {name: preset.to_dict() for name, preset in PRESETS.items()}
